all: # You can choose either 'amb' or 'native' here (Please see the group_vars folder and file names for each bridge, 'all' will deloy both)
  children:
    oracle:
      children:
        native:
          hosts:
            X.X.X.X: # Ip address or Hostname of the server
              ansible_user: root # Or whatever you like
              ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY: "Assume I have put my PrivateKey here" # Validator PrivateKey
        amb:
          hosts:
            X.X.X.X: # Ip address or Hostname of the server
              ansible_user: root # Or whatever you like
              ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY: "Assume I have put my PrivateKey here" # Validator PrivateKey



## EX: Below yaml will deploy 'xdai' bridge-validator

# native: 
#   children:
#     oracle:
#       children:
#         native:
#           hosts:
#             X.X.X.X: # Ip address or Hostname of the server
#               ansible_user: root # Or whatever you like
#               ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY: "Assume I have put my PrivateKey here" # Validator PrivateKey


## EX: Below yaml will deploy 'amb' bridge-validator

# amb: 
#   children:
#     oracle:
#       children:
#         amb:
#           hosts:
#             X.X.X.X: # Ip address or Hostname of the server
#               ansible_user: root # Or whatever you like
#               ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY: "Assume I have put my PrivateKey here" # Validator PrivateKey
