global:
  scrape_interval:     60s
  evaluation_interval: 30s
  scrape_timeout: 30s

  # external_labels:
  #     monitor: 'exporter-metrics'

# rule_files:
#   - 'test-alert.test'
#   - 'alert.rules.host'
#   - 'alert.rules.prod'


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]


scrape_configs:
  
  - job_name: 'production'
    scrape_interval: 30s
    scrape_timeout: 15s
    static_configs:
      - targets:
        - 'localhost:9090'
        labels:
          server: PRODUCTION
      - targets:
        - 'cadvisor:8080'
        labels:
          server: PRODUCTION
      - targets:
        - 'node-exporter:9100'
        labels:
          server: PRODUCTION
      - targets:
        - 'router:8000'
        labels:
          server: PRODUCTION

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090','node-exporter:9100']
